---
all:
  vars:
    ansible_user: vagrant 
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_python_interpreter: /usr/bin/python3
prod:
  hosts:
    client1:
      ansible_host: 10.0.0.11
    client2:  
      ansible_host: 10.0.0.12
  vars:
    ansible_password: vagrant
    env: production